version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: spmdb
    ports:
      - 5432:5432 
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dockernet

  spm-api:
    build: 
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - dockernet

volumes:
  db_data:

networks:
  dockernet:
    external: true
