version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: spmdb
    ports:
      - 5499:5432 
    volumes:
      - db_data:/var/lib/postgresql/data
  
  spm-api:
    build: 
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  db_data: